/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F177_4653();
extern void F179_4815();
extern void F177_4657();
extern void F174_4486();
extern void F176_4650();
extern void F174_4491();
extern void F223_2633();
extern void F213_4332();
extern void F29_691();
extern EIF_REFERENCE F29_678();
extern EIF_BOOLEAN F29_690();
extern EIF_BOOLEAN F29_698();
extern void F29_700();
extern void F29_701();
extern void F29_702();
extern void F34_810();
extern EIF_TYPED_VALUE F34_811();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F177_4653;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F177_4657;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F174_4486;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F174_4491;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F223_2633;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F179_4815;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F176_4650;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F213_4332;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F29_691;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F29_690;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F29_678;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F29_698;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F29_700;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F29_701;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F29_702;

	egc_str_dtype = 178;

	egc_immstr8_dtype = 177;

	egc_str32_dtype = 175;

	egc_immstr32_dtype = 174;
	egc_arr_dtype = 222;
	egc_tup_dtype = 127;
	egc_disp_rout_id = 1033;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0186;
	egc_sp_wchar = 0x0237;
	egc_sp_bool = 0x01AA;
	egc_sp_uint8 = 0x0162;
	egc_sp_uint16 = 0x026B;
	egc_sp_uint32 = 0x02E7;
	egc_sp_uint64 = 0x01F1;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x01C0;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x012F;
	egc_sp_real64 = 0x02C1;
	egc_sp_pointer = 0x010B;
	egc_sp_ref = 0xDA;

	egc_uint8_dtype = 150;
	egc_uint16_dtype = 147;
	egc_uint32_dtype = 144;
	egc_uint64_dtype = 141;
	egc_int8_dtype = 138;
	egc_int16_dtype = 135;
	egc_int32_dtype = 132;
	egc_int64_dtype = 129;
	egc_bool_dtype = 165;
	egc_real32_dtype = 153;
	egc_char_dtype = 162;
	egc_wchar_dtype = 159;
	egc_real64_dtype = 156;
	egc_point_dtype = 168;

	egc_exception_dtype = 46;
	egc_except_emnger_dtype = 28;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_factory";
	egc_system_location = "D:\\prod\\simple_factory\\EIFGENs\\simple_factory_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1768833077;
	egc_has_old_special_semantic = 0;
	scount = 776;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "TEST_SIMPLE_FACTORY.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 518;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 33;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F34_810;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F34_811;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 13; /* TEST_SIMPLE_FACTORY */
	}
}

#ifdef __cplusplus
}
#endif
